In [ ]:
import numpy as np
 
def sigmoid(x):
    # Наша функция активации: f(x) = 1 / (1 + e^(-x))
    return 1 / (1 + np.exp(-x))
 
class Neuron:
    def __init__(self, w, b):
        self.w = w
        self.b = b
 
    def feedforward(self, inputs):
        # Вводные данные о весе, добавление смещения и последующее использование функции активации
        total = np.dot(self.w, inputs) + self.b
        return sigmoid(total)
 
 
w = np.array([1, 1])
b = -1

n = Neuron(w, b)
 
x = np.array([0, 0])
print(n.feedforward(x))






0.2689414213699951


In [ ]:

 
class OurNeuralNetwork:
   
    def __init__(self):
        weights = np.array([1, 1])
        b = 0
 
        # Класс Neuron из предыдущего раздела
        self.h1 = Neuron(weights, b)
        self.h2 = Neuron(weights, b)
        self.o1 = Neuron(weights, b)
 
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
 
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2]))         # Вводы для о1 являются выводами h1 и h2
        return out_o1

 
x = np.array([2, 3]) 
network = OurNeuralNetwork()
print(network.feedforward(x)) 




0.8793844859243165


In [ ]:
import numpy as np
 
 
def mse_loss(y_true, y_pred):
    # y_true и y_pred являются массивами numpy с одинаковой длиной
    return ((y_true - y_pred) ** 2).mean()
 
 
y_true = np.array([1, 0, 0, 1])
y_pred = np.array([1, 0, 0, 1])
 
print(mse_loss(y_true, y_pred))  # 0.5




0.0


In [ ]:
a = [1, 3, 5, 7, 9]
b = [1, 1, 1, 1, 1]
d = [1, 1, 1, 1, 1]
c = []

for x,y,z in zip(a,b,d):
    print(x+y+z)







3
5
7
9
11


In [ ]:
import numpy as np
def new_func(a):
    return a
b = np.array([[1,2,3], [0,1,1], [2,3,4]])
print(b)
np.apply_along_axis(sum, 0, b)




[[1 2 3]
 [0 1 1]
 [2 3 4]]


array([3, 6, 8])